name: bpssulsel
description: SISOLA KI (Sistem InformaSI Online Laporan Kinrja Pegawai) App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.5.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.17.0
  crypto: ^3.0.6
  uuid: ^4.5.1
  excel: 4.0.6
  path: 1.9.1
  pdf: 3.11.3
  intl: 0.20.2
  timezone: 0.10.0
  shelf_cors_headers: 0.1.5
  barcode: ^2.2.9
  cron: ^0.6.2
  duration: ^4.0.3

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
